database:
    host: ''
    port: ''
    user: ''
    password: ''
    database: 'musicbro2_prod'
logger:
    name: 'musicbro'
    config: '..\config\logging_template.yaml'
lastfm:
    token: ''
    per_page: 1000