database:
    host: ...
    port: ...
    user: ...
    password: ...
    database: 'musicbro2_prod'
logger:
    name: 'musicbro'
    config: '..\config\logging.yaml'
lastfm:
    token: ...
    per_page: 1000
discogs:
    token: ...
    requests per second: 1
telegram:
    token: ...
    proxy: ...
tracked artists:
    A1 threshold: 300
    A2 threshold: 100
    B1 threshold: 50
    listening threshold: 730
conversations:
    report past releases: 239