FROM python:3.7.3-slim-stretch

RUN python -m pip install --upgrade pip && pip install --upgrade setuptools

RUN mkdir /musicbro2
WORKDIR /musicbro2

COPY ./requirements.txt /musicbro2/requirements.txt

RUN pip install -r requirements.txt

CMD ["python"]